import "./globals.css";
import type { Metadata } from "next";
// import { Inter } from "next/font/google";

import { ClerkProvider } from "@clerk/nextjs";
import { GlobalContextProvider } from "./context";

// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Certificate Verification System",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <GlobalContextProvider>
      <ClerkProvider afterSignOutUrl="/">
        <html lang="en">
          <body>{children}</body>
        </html>
      </ClerkProvider>
    </GlobalContextProvider>
  );
}
